### ISSUE TITLE
Some zonedDateTimes throw error on add method 

### ISSUE THREAD

**Issue by bradley-pettman** [rubber-duck-software/iso-fns#50]
I am trying to use the `zonedDateTimeFns.add()` method and am finding that certain dates are returning an error message saying either **"date value is not finite in DateTimeFormat format()"** or **"Invalid Receiver"**.  

For example, adding 1 day to the zonedDateTime `2019-03-09T00:00:00.000-06:00[America/Chicago]` works: 
<img width="1323" alt="Screen Shot 2021-12-22 at 9 16 53 AM" src="https://user-images.githubusercontent.com/86842931/147114521-854164b3-652e-4f79-bb23-a014682e1f32.png">

But, the same operation on just one day later (i.e. `2019-03-09T00:00:00.000-06:00[America/Chicago]`) fails: 
<img width="1343" alt="Screen Shot 2021-12-22 at 9 17 59 AM" src="https://user-images.githubusercontent.com/86842931/147114669-efbd97cf-3852-4713-94b9-e77b4fdee95c.png">

I am not able to see the pattern for which dates throw an error, but here are a few examples:
`'2020-03-08T00:00:00.000-06:00[America/Chicago]'` (date value is not finite)
`'2000-10-08T00:00:00.000-06:00[America/Chicago]'` (invalid receiver)
`'2021-03-14T00:00:00.000-06:00[America/Chicago]'` (date value is not finite)
`'2021-03-15T00:00:00.000-06:00[America/Chicago]'` (invalid receiver)

**Comment by rubber-duck-software** [comment]
Hi @bradley-pettman! Thanks for identifying this bug. We and putting the fix out now

**Comment by rubber-duck-software** [comment]
Fixed in 2.0.0-alpha.1
