### ISSUE TITLE
Conversion function from monthDay and yearMonth to date, dateTime, Instant, and zonedDateTime

### ISSUE THREAD

**Issue by kolton-musgrove** [rubber-duck-software/iso-fns#56]
There should be a function to easily convert from the monthDay and yearMonth types to the other types by supplying the monthDay or yearMonth and the other required properties.

**Comment by rubber-duck-software** [comment]
If I am understanding this right, would `yearMonthFns.toDate(day: number)` and `monthDayFns.toDate(year: number)` cover this use case?
