### ISSUE TITLE
dateFns.isEqual() doesn't work

### ISSUE THREAD

**Issue by bradley-pettman** [rubber-duck-software/iso-fns#62]
I am finding that, no matter which days I compare using `dateFns.isEqual()`, I am getting a `true` result.

Below is just one example:

<img width="1308" alt="Screen Shot 2021-12-30 at 1 51 57 PM" src="https://user-images.githubusercontent.com/86842931/147784034-b8ada107-c27c-4ad2-b9d0-b68c46391b50.png">

**Comment by rubber-duck-software** [comment]
Fixed in alpha.5
