### ISSUE TITLE
durationFns.round() largestUnit option does not accept plural units

### ISSUE THREAD

**Issue by kolton-musgrove** [rubber-duck-software/iso-fns#75]
})
    it('accepts singular units', () => {
      assert.equal(`${durationFns.round(d, { largestUnit: 'year', relativeTo })}`, `${durationFns.round(d, { largestUnit: 'years', relativeTo })}`)
      assert.equal(`${durationFns.round(d, { smallestUnit: 'year', relativeTo })}`, `${durationFns.round(d, { smallestUnit: 'years', relativeTo })}`)
      assert.equal(`${durationFns.round(d, { largestUnit: 'month', relativeTo })}`, `${durationFns.round(d, { largestUnit: 'months', relativeTo })}`)
      assert.equal(`${durationFns.round(d, { smallestUnit: 'month', relativeTo })}`, `${durationFns.round(d, { smallestUnit: 'months', relativeTo })}`)
      assert.equal(`${durationFns.round(d, { largestUnit: 'day', relativeTo })}`, `${durationFns.round(d, { largestUnit: 'days', relativeTo })}`)
      assert.equal(`${durationFns.round(d, { smallestUnit: 'day', relativeTo })}`, `${durationFns.round(d, { smallestUnit: 'days', relativeTo })}`)
      assert.equal(`${durationFns.round(d, { largestUnit: 'hour', relativeTo })}`, `${durationFns.round(d, { largestUnit: 'hours', relativeTo })}`)
      assert.equal(`${durationFns.round(d, { smallestUnit: 'hour', relativeTo })}`, `${durationFns.round(d, { smallestUnit: 'hours', relativeTo })}`)
      assert.equal(`${durationFns.round(d, { largestUnit: 'minute', relativeTo })}`, `${durationFns.round(d, { largestUnit: 'minutes', relativeTo })}`)
      assert.equal(
        `${durationFns.round(d, { smallestUnit: 'minute', relativeTo })}`,
        `${durationFns.round(d, { smallestUnit: 'minutes', relativeTo })}`
      )
      assert.equal(`${durationFns.round(d, { largestUnit: 'second', relativeTo })}`, `${durationFns.round(d, { largestUnit: 'seconds', relativeTo })}`)
      assert.equal(
        `${durationFns.round(d, { smallestUnit: 'second', relativeTo })}`,
        `${durationFns.round(d, { smallestUnit: 'seconds', relativeTo })}`
      )
      assert.equal(
        `${durationFns.round(d, { largestUnit: 'millisecond', relativeTo })}`,
        `${durationFns.round(d, { largestUnit: 'milliseconds', relativeTo })}`
      )
      assert.equal(
        `${durationFns.round(d, { smallestUnit: 'millisecond', relativeTo })}`,
        `${durationFns.round(d, { smallestUnit: 'milliseconds', relativeTo })}`
      )
    })

None of the plural units are accepted.

**Comment by rubber-duck-software** [comment]
Fixed in #80
