### ISSUE TITLE
Sum two times

### ISSUE THREAD

**Issue by theprobugmaker** [rubber-duck-software/iso-fns#93]
Working with timestamps in JavaScript has been a pain in the 🍑 . I don't know if I'm doing something wrong or if it's really complicated.

I'm going to write in plain JS what I want to do and I need help making it easier on `iso-fns` if possible.

JS doesn't have a `Time` format, only `Date`, so if I want to create a date with the time as `00:00:00` I would need something like this:

```js
const a = new Date()
a.setHours(0, 0, 0, 0)
```

I can't just `new Date("00:00:00")` otherwise I get a `Invalid Date` message.

Now Imagine that I want to sum two times. `00:00:00` and `00:30:00`. If you try this:

```js
const a = new Date()
a.setHours(0, 0, 0, 0)

const b = new Date()
b.setHours(0, 30, 0, 0)

const c = a + b
```

`c` is now a string 😞 

But let's try using an approach that seems to be the right one:

```js
const a = new Date()
a.setHours(0, 0, 0, 0)

const b = new Date()
b.setHours(0, 30, 0, 0)

const c = new Date(a.getTime() + b.getTime())
```

The result is funny, the year is now `2074`, the hour is like `03:30:00` (it might differ for you), but not even close to what we wanted.

The only way I could make it work was doing something like this:

```js
const a = new Date()
a.setHours(0, 0, 0, 0)

const b = new Date()
b.setHours(0, 30, 0, 0)

const c = new Date()
c.setHours(a.getHours() + b.getHours())
c.setMinutes(a.getMinutes() + b.getMinutes())
c.setSeconds(a.getSeconds() + b.getSeconds())
```

Now we have the right sum of times.

Is there a better way of doing that? Is there a way that `iso-fns` can help me with that? Thank you very much.

**Comment by rubber-duck-software** [comment]
Apologies for the late reply- I'm a graduate student and the end of the semester hits hard 😂. This is exactly the problem iso-fns is solving. iso-fns is multi-domain, meaning it has not one, but eight different date time types 

1. Instant: a fixed point in time without regard to calendar or location, e.g. July 20, 1969, at 20:17 UTC.
2. ZonedDateTime: a timezone-aware date/time that represents a real event that has happened (or will happen) at a particular exact time from the perspective of a particular region on Earth, e.g. December 7th, 1995 at 3:24 AM in US Pacific time.
3. DateTime: represents a calendar date and wall-clock time that does not carry time zone information, e.g. December 7th, 1995 at 3:00 PM.
4. Date: represents a calendar date that is not associated with a particular time or time zone, e.g. August 24th, 2006.
5. Time: represents a wall-clock time that is not associated with a particular date or time zone, e.g. 7:39 PM.
6. YearMonth: A date without a day component. This is useful to express things like "the October 2020 meeting".
7. MonthDay: A date without a year component. This is useful to express things like "Bastille Day is on the 14th of July".
8. Duration: expresses a length of time, e.g. 5 minutes and 30 seconds. This is used for date/time arithmetic and for measuring differences between two dates/times.

Your example in iso-fns would look like 
```js
timeFns.add("00:00", {minutes: 30}) // "00:30"
```
